# Generated by Django 3.0 on 2021-04-09 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_brand', models.CharField(choices=[('calvin klein', 'calvin klein'), ('gucci', 'gucci'), ('true religion', 'true religion'), ('burberry prorsum', 'burberry prorsum'), ('dolce&gabbana', 'dolce&gabbana'), ('armani', 'armani')], max_length=100)),
                ('Product_model', models.CharField(max_length=100)),
                ('Product_price', models.IntegerField()),
                ('Product_desc', models.TextField()),
                ('Product_image', models.ImageField(upload_to='Product_image')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
    ]
