# Generated by Django 3.0 on 2021-06-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_brand',
            field=models.CharField(choices=[('calvin klein', 'calvin klein'), ('gucci', 'gucci'), ('true religion', 'true religion'), ('burberry prorsum', 'burberry prorsum'), ('dolce&gabbana', 'dolce&gabbana'), ('armani', 'armani'), ('being human', 'being human')], max_length=100),
        ),
    ]
